name: Deploy Documentation Website

on: workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Build API documentation"
        run: ./gradlew dokkaGeneratePublicationHtml

      - name: "Add API docs to mkdocs structure"
        run: mv ./build/dokka/html/ ./docs/api/

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: "Build and deploy documentation website"
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force
