name: Run Tests
on: [workflow_dispatch, pull_request]

jobs:
  test:
    name: "Test library"
    runs-on: ubuntu-22.04

    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v2

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: "Run tests"
        run: ./gradlew test --console=plain
